print ("Knock Knock")
input ()
input ("Who's there")
input ()
print ("lettuce")
input ()
input ("lettuce what?")
input ()
print ("let us in...")
input ()
print ("what do cows say when you're unfunny?")
input ()
print ("im not a-moo-sed...")
input ()
print ("why did the golfer wear two pairs of pants?")
input ()
print ("in case he got a hole in one...")
input ()
print ("why are elephants wrinkly")
input ()
print ("because you can't iron them...")
input ()
print ("what does that mean")
input ()
print ("goodbye...")
name = input ("whats your name")
print (f"goodbye {name}, goodbye...")
input ()
print ("the end!")