print ("hi we're going to write a story")
input ("okay..?")
print ("press enter to continue and when you're finished writing.")
input ()
name = input ("tell me your name")
input ()
print ("okay...")
where = input ("now tell me a location..like a state or country.")
input ()
print ("okay.")
what = input ("tell me an animal")
if what == "cat":
    print ("i love cats...")
input ()
print ("okay...")
feeling = input ("now tell me a feeling")
input ()
print ("okay.")
song = input ("now tell me your favorite song")
input ()
print ("okay...")
saying = input ("now tell me a little saying..like [oh my!]")
input ()
print ("okay.")
adjective = input ("tell me an adjective")
input ()
print ("okay...")
dislike = input ("now tell me something you dislike")
input ()
print ("okay.")
saying2 = input ("now tell me ANOTHER saying")
input ()
print ("okay!")
print ("time to hear your story!")
input ()
print (f"my name is {name}")
input ()
print (f"today im going to the {where} zoo")
input ()
print (f"i saw a {what}!!")
input ()
print (f"now im feeling {feeling}")
input ()
print (f"at first i wanted to stay home and listen to {song}")
input ()
print (f"but {saying}! the zoo is so {adjective}!")
input ()
print (f"but then...I saw a {dislike}")
input ()
print (f"{saying2} i guess i have to leave...")
input ()
print (f"thank you for doing my mad-libs {name}!!")
input ()
print ("thank you...bye...")
input ()
print ("bye...")