print ("hi were going to write a story")
input ("okay..?")
name = input ("tell me a name or your name")
input ()
print ("okay...")
input ()
where = input ("now tell me a location..like a state or country.")
input ()
print ("okay.")
input ()
what = input ("tell me an animal")
input ()
print ("okay...")
input ()
feeling = input ("now tell me a feeling")
input ()
print ("okay.")
input ()
song = input ("now tell me your favorite song")
input ()
print ("okay...")
input ()
saying = input ("now tell me a little saying..like [oh my!]")
input ()
print ("okay.")
input ()
adjective = input ("tell me an adjective")
input ()
print ("okay...")
input ()
dislike = input ("now tell me something you dislike")
input ()
print ("okay.")
input ()
saying2 = input ("now tell me ANOTHER saying")
input ()
print ("okay!")
input ()
print ("time to hear your story!")
input ()
print (f"my name is {name}")
input ()
print (f"today im going to the {where} zoo")